version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog
      - ./logs/zookeeper:/opt/bitnami/zookeeper/logs

  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    restart: on-failure
    ports:
      - 9093:9093
      - 29093:29093
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093,PLAINTEXT_HOST://:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9093,PLAINTEXT_HOST://localhost:29093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_REPLICATION_FACTOR=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./data/kafka1:/var/lib/kafka/data
      - ./logs/kafka1:/opt/bitnami/kafka/logs
#      - ./info/kafka1:/bitnami/kafka/data
    depends_on:
      - zookeeper

  kafka2:
    image: bitnami/kafka:latest
    container_name: kafka2
    restart: on-failure
    ports:
      - 9094:9094
      - 29094:29094
    environment:
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9094,PLAINTEXT_HOST://:29094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9094,PLAINTEXT_HOST://localhost:29094
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_REPLICATION_FACTOR=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./data/kafka2:/var/lib/kafka/data
      - ./logs/kafka2:/opt/bitnami/kafka/logs
#      - ./info/kafka2:/bitnami/kafka/data
    depends_on:
      - zookeeper

  kafka3:
    image: bitnami/kafka:latest
    container_name: kafka3
    restart: on-failure
    ports:
      - 9095:9095
      - 29095:29095
    environment:
      - KAFKA_CFG_BROKER_ID=3
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9095,PLAINTEXT_HOST://:29095
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9095,PLAINTEXT_HOST://localhost:29095
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_REPLICATION_FACTOR=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./data/kafka3:/var/lib/kafka/data
      - ./logs/kafka3:/opt/bitnami/kafka/logs
#      - ./info/kafka3:/bitnami/kafka/data
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka1
      - kafka2
      - kafka3
      - zookeeper
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=cluster-wm
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9093,kafka2:9094,kafka3:9095
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    volumes:
      - ./data/kafka-ui:/app/kafka-ui
      - ./logs/kafka-ui:/var/log/kafka-ui